### PR TITLE
Brazilian portuguese translation

### PR DESCRIPTION
**Pull request by gjalves**
This is an adaptation from Portuguese (pt) to Brazilian portuguese (pt_BR) translation

### CODE REVIEW

**Comment by freeheel3r** [comment]
Obrigado!
I noticed there are a few translations missing (in both pt and pt_BR) -- would you like to complete those? If not I'll just merge this pull request.

**Comment by gjalves** [comment]
I'll be doing this today.

Best Regards,

Gustavo

Em 10-05-2016 04:13, Craig escreveu:

**Comment by freeheel3r** [comment]
Thanks a lot for your contribution!

I'm afraid I didn't notice your latest update before releasing 1.3.1, so the translations will be included in the next official release.

**Comment by alexrsoares** [comment]
I have finished an updated version for Brazilian Portuguese (pt_BR) based on English (en_GB) and French (fr_CH) versions.
It's available here:
[https://docs.zoho.com/file/oifyxceec5eff3751418187839da9f3c58a79](url)

**Pull request merged**
